dist_encoding = {'Ciutat Vella': 0,
 'Eixample': 1,
 'Gracia': 2,
 'Horta-Guinardo': 3,
 'Les Corts': 4,
 'Nou Barris': 5,
 'Sant Andreu': 6,
 'Sant Marti': 7,
 'Sants-Montjuic': 8,
 'Sarria-Sant Gervasi': 9}

neigh_encoding = {'Baro de Viver': 0,
 'Can Baro': 1,
 'Can Peguera': 2,
 'Canyelles': 3,
 'Ciutat Meridiana': 4,
 'Diagonal Mar i el Front Maritim del Poblenou': 5,
 'Fort Pienc': 6,
 'Gothic Quarter': 7,
 'Horta': 8,
 'Hostafrancs': 9,
 'Montbau': 10,
 'Navas': 11,
 'Pedralbes': 12,
 'Porta': 13,
 'Provencals del Poblenou': 14,
 'Sagrada Familia': 15,
 'Sant Andreu': 16,
 'Sant Antoni': 17,
 'Sant Genis dels Agudells': 18,
 'Sant Gervasi - Galvany': 19,
 'Sant Gervasi - la Bonanova': 20,
 'Sant Marti de Provencals': 21,
 'Sant Martíide Provencals': 22,
 'Sant Pere, Santa Caterina i la Ribera': 23,
 'Sants': 24,
 'Sants - Badal': 25,
 'Sarria': 26,
 'Torre Baro': 27,
 'Vallbona': 28,
 'Vallcarca i els Penitents': 29,
 'Vallvidrera, el Tibidabo i les Planes': 30,
 'Verdun': 31,
 'Vilapicina i la Torre Llobeta': 32,
 'el Baix Guinardo': 33,
 'el Besos i el Maresme': 34,
 'el Bon Pastor': 35,
 "el Camp d'en Grassot i Gracia Nova": 36,
 "el Camp de l'Arpa del Clot": 37,
 'el Carmel': 38,
 'el Clot': 39,
 'el Coll': 40,
 'el Congres i els Indians': 41,
 'el Guinardo': 42,
 'el Parc i la Llacuna del Poblenou': 43,
 'el Poble Sec': 44,
 'el Poblenou': 45,
 'el Putxet i el Farro': 46,
 'el Raval': 47,
 'el Turo de la Peira': 48,
 "l'Antiga Esquerra de l'Eixample": 49,
 'la Barceloneta': 50,
 'la Bordeta': 51,
 'la Clota': 52,
 "la Dreta de l'Eixample": 53,
 "la Font d'en Fargues": 54,
 'la Font de la Guatlla': 55,
 'la Guineueta': 56,
 'la Marina de Port': 57,
 'la Marina del Prat Vermell': 58,
 'la Maternitat i Sant Ramon': 59,
 "la Nova Esquerra de l'Eixample": 60,
 'la Prosperitat': 61,
 'la Sagrada Familia': 62,
 'la Sagrera': 63,
 'la Salut': 64,
 'la Teixonera': 65,
 'la Trinitat Nova': 66,
 'la Trinitat Vella': 67,
 "la Vall d'Hebron": 68,
 'la Verneda i la Pau': 69,
 'la Vila Olimpica del Poblenou': 70,
 'la Vila de Gracia': 71,
 'les Corts': 72,
 'les Roquetes': 73,
 'les Tres Torres': 74}

rent_encoding = {'average rent (euro/month)': 0, 'average rent per surface (euro/m2)': 1}

year_var = [i for i in range(2014, 2023)]

trimester_var = [1, 2, 3, 4]


intro = '''
Discover a game-changing solution for predicting Barcelona rent prices. 
Our project combines state-of-the-art machine learning, a FastAPI-based 
ML model, and a user-friendly Streamlit frontend to provide highly accurate 
predictions with a 98% success rate. Whether you're a landlord seeking optimal 
pricing or a tenant looking for fair deals, our platform revolutionizes real estate decision-making.
'''